spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://10.0.0.8:3306/crawler?useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://localhost:3306/crawler?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
#    password: pamo
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 50
    min-idle: 5
    initial-size: 5
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.frame.process.model
    configLocation: classpath:/mybatis/mybatis-config.xml
    
mapper:
    mappers: com.frame.process.core.MyMapper
    identity: MYSQL
    
commonProcess: 
    modelPackage: com.frame.process.model
    fileLocation: C:/Users/Administrator/Desktop/test